global:
  scrape_interval:     15s 

  
  
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name:       'node'
 
    scrape_interval: 5s

    static_configs:
      - targets: ['node-exporter-1:9100', 'node-exporter-2:9100']
        labels:
          group: 'production'

      - targets: ['node-exporter-3:9100']
        labels:
          group: 'canary'